apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proyecto-pvc
  namespace: my-namespace
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #se puede ajustar dependiendo el tamaño del proyecto